### ISSUE TITLE
Rendering glitch with placed structures containing fences

### ISSUE THREAD

**Issue by antiphysika** [matthewperiut/fence_on_slab#1]
Minecraft version: 1.21
NeoForge version: 21.0.21-beta
Mod version: 0.1.0

Unsure if this is a conflict with Explorify or not, but I'm seeing a rendering glitch with structures paced in the world that contain fences that looks something like this:

![Screenshot](https://gcdnb.pbrd.co/images/KCZajVB4BRx1.png?o=1)
![Screenshot](https://gcdnb.pbrd.co/images/ip8HyHBg6iZO.png?o=1)

Removing the Fence On Slab mod from my test instance fixes the glitch. I've also confirmed that resource packs are in the correct order as per the troubleshooting section of the Curseforge page just in case.

I've uploaded a log from the smallest instance (two mods) where I could reproduce this [here](https://gist.github.com/antiphysika/1fedecda5044210b6052108b4d47711d). In case it's helpful, my testing seed is 5507530435203425913 and the structure from the screenshots above can be found at coords X:109 Y:74 Z:73.

Am I at the right Github, or should I darken the other mod dev's door? :grin:

Cheers!

**Comment by matthewperiut** [comment]
Thanks for the report, I'm assuming it's on my end I'm pretty sure. I'll go and take a look!

**Comment by matthewperiut** [comment]
I finally uploaded all the 0.1.1 versions on CurseForge, Modrinth, and GitHub. Unfortunately already generated structures will have these weird fences, you just need to break them and place them again. Newly generated structures and worlds will all have the correct fence.

**Comment by antiphysika** [comment]
Awesome. Thanks for the speedy fix and the mod itself! :grin:
